services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/phoenix"
      - "/phoenix/tmp"
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
